In [4]:
import numpy as np
print("version of pandas is",np.__version__)

version of pandas is 1.25.2


In [26]:
a = []
nums = int(input("total number in ur number: "))
for i in range(nums):
    x = int(input("give me:"))
    a.append(x)
np_arr = np.array(a)
print(np_arr)
even = []
odd = []
for i in range(nums):
    if(np_arr[i-1] % 2 ==0):
        even.append(np_arr[i-1])
    else:
        odd.append(np_arr[i-1])
np_even = np.array(even)
np_odd  = np.array(odd)
print(np_even)
print(np_odd)

total number in ur number:  3
give me: 1
give me: 2
give me: 3


[1 2 3]
[2]
[3 1]


In [28]:
arr_1d = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
arr_2d = arr_1d.reshape((2, -1))
print(arr_2d)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [41]:
arr1 = np.array([2,3,6,7])
arr2 = np.array([5,3,7,9])
# def intersection(lst1, lst2):
 
#     # Use of hybrid method
#     temp = set(lst2)
#     lst3 = [value for value in lst1 if value in temp]
#     return lst3

# list1  = intersection(arr1,arr2)
# print(list1)

# x = np.where(arr1 == (list1))
# np.delete(arr1,x)
# print(x)

result = np.setdiff1d(arr1,arr2)
print(result)

[2 6]


In [42]:
a = np.array([1, 2, 3, 4, 5, 6])
b = np.array([2, 3, 4, 5, 6, 7])

positions = np.where(a == b)

print(positions)


(array([], dtype=int64),)
